// @ts-check
// Cynhyrchwyd y ffeil hon yn awtomatig. PEIDIWCH Â MODIWL
// This file is automatically generated. DO NOT EDIT

export function CreateDir(arg1) {
  return window['go']['main']['App']['CreateDir'](arg1);
}

export function CreateFile(arg1) {
  return window['go']['main']['App']['CreateFile'](arg1);
}

export function GetUserHomeDir() {
  return window['go']['main']['App']['GetUserHomeDir']();
}

export function ListDir(arg1, arg2) {
  return window['go']['main']['App']['ListDir'](arg1, arg2);
}

export function OpenFileInSublimeText(arg1) {
  return window['go']['main']['App']['OpenFileInSublimeText'](arg1);
}

export function OpenFileInVSCode(arg1) {
  return window['go']['main']['App']['OpenFileInVSCode'](arg1);
}

export function OpenImageInFeh(arg1) {
  return window['go']['main']['App']['OpenImageInFeh'](arg1);
}

export function OpenPdfInXDG(arg1) {
  return window['go']['main']['App']['OpenPdfInXDG'](arg1);
}

export function RemoveFile(arg1) {
  return window['go']['main']['App']['RemoveFile'](arg1);
}
