// Cynhyrchwyd y ffeil hon yn awtomatig. PEIDIWCH Â MODIWL
// This file is automatically generated. DO NOT EDIT
import {main} from '../models';

export function CreateDir(arg1:string):Promise<void>;

export function CreateFile(arg1:string):Promise<void>;

export function GetUserHomeDir():Promise<string>;

export function ListDir(arg1:string,arg2:main.AdditionalParams):Promise<Array<main.FileStruct>>;

export function OpenFileInSublimeText(arg1:string):Promise<void>;

export function OpenFileInVSCode(arg1:string):Promise<void>;

export function OpenImageInFeh(arg1:string):Promise<void>;

export function OpenPdfInXDG(arg1:string):Promise<void>;

export function RemoveFile(arg1:string):Promise<void>;
