// Cynhyrchwyd y ffeil hon yn awtomatig. PEIDIWCH Â MODIWL
// This file is automatically generated. DO NOT EDIT
import {main} from '../models';

export function GetUserHomeDir():Promise<string>;

export function ListDir(arg1:string,arg2:main.AdditionalParams):Promise<Array<main.FileStruct>>;
