// @ts-check
// Cynhyrchwyd y ffeil hon yn awtomatig. PEIDIWCH Â MODIWL
// This file is automatically generated. DO NOT EDIT

export function GetUserHomeDir() {
  return window['go']['main']['App']['GetUserHomeDir']();
}

export function ListDir(arg1, arg2) {
  return window['go']['main']['App']['ListDir'](arg1, arg2);
}
